### ISSUE TITLE
KeyError: 'entries'

### ISSUE THREAD

**Issue by Ji4n1ng** [JustusW/harparser#7]
I got a har file from Charles(a web debugging proxy application). This file can be opened by HTTP Archive Viewer. But it cannot be parsed by harparser.

Console:
```
Traceback (most recent call last):
  File "harToAstra.py", line 4, in <module>
    my_har = HAR.log().json(har_string)
  File "/home/jianing/Program/Python/HarToAstra/src/harparser/harparser.py", line 102, in json
    return self.__init__(loads(json_string))
  File "/home/jianing/Program/Python/HarToAstra/src/harparser/harparser.py", line 35, in __init__
    self[key]
  File "/home/jianing/Program/Python/HarToAstra/src/harparser/harparser.py", line 77, in __getitem__
    return self.__dict__.__getitem__(*args, **kwargs)
KeyError: 'entries'
```

My code:
```
from harparser import HAR
har_string = open('test.json').read()
my_har = HAR.log().json(har_string)
```

I don't know why it went wrong. I hope you can help me. Thanks.

**Comment by JustusW** [comment]
Could you kindly supply the JSON file you are trying to parse? The Entries attribute is indeed mandatory (not marked as optional in the 1.2 HAR specification). It may be empty but must not be omitted. The Entries Attribute is the primary source of data in a HAR file, even if you only store Pages you should have one request per Page minimum.

**Comment by Ji4n1ng** [comment]
Thanks for replying me. I have solved my problem by using JSON to parse directly. 

I took a part of the file and placed it below.

```
{
    "log": {
        "version": "1.2",
        "creator": {
            "name": "Charles Proxy",
            "version": "4.2.6"
        },
        "entries": [
            {
                "startedDateTime": "2018-09-07T15:44:27.839+08:00",
                "time": 131012,
                "request": {
                    "method": "CONNECT",
                    "url": "https://31.13.75.17",
                    "httpVersion": "HTTP/1.1",
                    "cookies": [],
                    "headers": [],
                    "queryString": [],
                    "headersSize": 0,
                    "bodySize": 0
                },
                "response": {
                    "_charlesStatus": "EXCEPTION",
                    "status": 503,
                    "statusText": "Error",
                    "httpVersion": "HTTP/1.0",
                    "cookies": [],
                    "headers": [
                        {
                            "name": "Server",
                            "value": "Charles"
                        },
                        {
                            "name": "Cache-Control",
                            "value": "must-revalidate,no-cache,no-store"
                        },
                        {
                            "name": "Content-Type",
                            "value": "text/html;charset=ISO-8859-1"
                        },
                        {
                            "name": "Content-Length",
                            "value": "930"
                        },
                        {
                            "name": "Connection",
                            "value": "close"
                        }
                    ],
                    "content": {
                        "size": 930,
                        "mimeType": "text/html;charset=ISO-8859-1",
                        "text": "<html>\n<head>\n    <title>Charles Error Report</title>\n    <style type=\"text/css\">\nbody {\n    font-family: Arial,Helvetica,Sans-serif;\n    font-size: 12px;\n    color: #333333;\n    background-color: #ffffff;\n}\n\nh1 {\n    font-size: 24px;\n    font-weight: bold;\n}\n\nh2 {\n    font-size: 18px;\n    font-weight: bold;\n}\n    </style>\n</head>\n<body>\n\n<h1>Charles Error Report</h1>\n<h2>Failed to connect to remote host</h2>\n<p>Charles failed to connect to the remote host. Check that your Internet connection is ok and that the remote host is accessible. Maybe your network uses a proxy server to access the Internet? You can configure Charles to use an external proxy server in the External Proxy Settings.</p>\n<p>The actual exception reported was:</p>\n<pre>\njava.net.ConnectException: ???? (Connection timed out)\n</pre>\n\n<p>\n<i>Charles Proxy, <a href=\"http://www.charlesproxy.com/\">http://www.charlesproxy.com/</a></i>\n</p>\n</body>\n</html>"
                    },
                    "redirectURL": null,
                    "headersSize": 0,
                    "bodySize": 930,
                    "comment": "Connection timed out"
                },
                "serverIPAddress": "31.13.75.17",
                "cache": {},
                "timings": {
                    "dns": 0,
                    "connect": -1,
                    "ssl": -1,
                    "send": -1,
                    "wait": -1,
                    "receive": -1
                }
            },
```
